# Generated by Django 5.0.6 on 2024-07-12 18:35

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_author_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.generate_upload_path),
        ),
    ]
